# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
### 헬스 체크
GET http://{{host}}/monitor/health

### 토큰 발급
POST http://{{host}}/api/1/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{username}} {{password}}

grant_type=naver&naver_id=33007614

> {% client.global.set("access_token", response.body.access_token); %}

### 상품 카테고리 조회
GET http://{{host}}/api/1/categories
Authorization: Bearer {{access_token}}


### 상품 목록 조회
GET http://{{host}}/api/1/posts/1
Authorization: Bearer {{access_token}}

> {% client.global.set("goods_no", response.body.goods[0].goods_no); %}


### 상품 목록 조회
GET http://{{host}}/api/1/goods?count=2&category=001
Authorization: Bearer {{access_token}}

### 상품 조회 with ID
GET http://{{host}}/api/1/goods/1000031418
Authorization: Bearer {{access_token}}

### 상품 좋아요
POST http://{{host}}/api/1/goods/1000028115/likes
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

### 상품 좋아요 취소
DELETE http://{{host}}/api/1/goods/1000031418/likes/1
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

### 상품 좋아요 취소
DELETE http://{{host}}/api/1/goods/1000031418/likes/1
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json


### 스토어 조회
GET http://{{host}}/api/1/stores/5
Authorization: Bearer {{access_token}}

### 스토어 좋아요
POST http://{{host}}/api/1/stores/6/likes
Authorization: Bearer {{access_token}}

### 스토어 좋아요 취소
DELETE http://{{host}}/api/1/stores/5/likes/1
Authorization: Bearer {{access_token}}

### 스토어 좋아요 목록 조회
GET http://{{host}}/api/1/members/me/likes?category=store
Authorization: Bearer {{access_token}}


### 추천 채널
GET http://{{host}}/api/1/recommendations/members?count=20
Authorization: Bearer {{access_token}}

### 추천 상품
GET http://{{host}}/api/1/recommendations/goods?count=20
Authorization: Bearer {{access_token}}

### 추천 MOTD
GET http://{{host}}/api/1/recommendations/motd?count=20
Authorization: Bearer {{access_token}}

### 상품 설명 페이지
GET http://{{host}}/api/1/goods/1000028665/details?includeVideo=true
Authorization: Bearer {{access_token}}

###