spring:
  config:
    activate:
      on-profile: dev
    import: classpath:application-oauth-dev.yml
  datasource:
    url: jdbc:mysql://localhost:3306/mybeautip?zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: mybeautip
    password: akdlqbxlq#1@Jocoos
    test-on-borrow: true
    validation-query: SELECT 1

mybeautip:
  security:
    access-token-validity-seconds: 604800     # 7 hours
    refresh-token-validity-seconds: 1814400    # 21 days
  slack:
    key: T03FMJ9ANNR/B03FMKSJLH3/Z8iTlyAygCiKz647cM1dZtMn
    channel: "#z-mybeautip-dev"
    order-key: T02GN94AU/BJA6YDJPJ/7L197lsrvR2X5yBsZpA2wdH0
    order-channel: "#z-mybeautip-dev"

logging:
  config: classpath:log/log4j2-file.yml
