spring:
  profiles: production
  datasource:
    url: jdbc:mysql://localhost:3306/mybeautip?zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: mybeautip
    password: akdlqbxlq#1@Jocoos
    test-on-borrow: true
    validation-query: SELECT 1
  flyway:
    baselineOnMigrate: false
    locations: classpath:db/mysql

mybeautip:
  security:
    access-token-validity-seconds: 3600      # 1 hours
    refresh-token-validity-seconds: 1800     # .5 hours
  iam:
    sns:
      access-key: AKIAIR6VYJSAQ5ROEGTA
      secret-key: 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
  aws:
    sns:
      application:
        gcm-arn: "arn:aws:sns:ap-northeast-2:776875668468:app/GCM/mybeautip-dev"

flipflop:
  app-key: testapp3
  video:
    thumbnail-format: https://s3.ap-northeast-2.amazonaws.com/flipflop/${flipflop.app-key}/videos/%s/thumbnail.jpg

logging:
  config: classpath:log/log4j2-file.yml