spring:
  security:
    oauth2:
      client:
        provider:
          kakao:
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            client-id: 24c07e1aa425eee8ff33dc762bb52578
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:3000/oauth/kakao
            state:
          naver:
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            client-id: u6IHjY5nYFx76BSlFxmC
            client-secret: S0Ss6qUwsP
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:3000/oauth/naver
            state: mybeautip-web-mobile