spring:
  security:
    oauth2:
      client:
        provider:
          kakao:
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            client-id: 704ba96c9232605e0c5a0294716e35be
            authorization-grant-type: authorization_code
          naver:
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            client-id: u6IHjY5nYFx76BSlFxmC
            client-secret: S0Ss6qUwsP
            authorization-grant-type: authorization_code
          facebook:
            token-uri: https://graph.facebook.com/v13.0/oauth/access_token
            token-method: GET
            user-info-uri: https://graph.facebook.com/me
            client-id: 1616911611764694
            client-secret: 7ed5aebdbcd0ed43efca4238a64c88be
            fields: id,email,name,picture