spring:
  config:
    activate:
      on-profile: plus-dev
    import: classpath:application-oauth-dev.yml
  datasource:
    master:
      hikari:
        username: mybeautipthdevsrv
        password: mybeautipthdevsrvpass44
        jdbc-url: jdbc:mysql://rds-mybeautip-plus-dev.cluster-conkqmswrjiq.ap-southeast-1.rds.amazonaws.com:13306/mybeautip?allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    slave:
      hikari:
        username: mybeautipthdevsrv
        password: mybeautipthdevsrvpass44
        jdbc-url: jdbc:mysql://rds-mybeautip-plus-dev.cluster-ro-conkqmswrjiq.ap-southeast-1.rds.amazonaws.com:13306/mybeautip?allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF-8&useSSL=false
mybeautip:
  store:
    image-path:
      domain: https://static.mybeautip.com/common/
  security:
    access-token-validity-seconds: 2592000     # 30 days
    refresh-token-validity-seconds: 1814400    # 21 days
  slack:
    key: T03FMJ9ANNR/B0505822V9N/fTaHxHs2bs39lo3Yxpv7xR3g
    channel: "#mybeautip-plus-dev"
    order-key: T03FMJ9ANNR/B0505822V9N/fTaHxHs2bs39lo3Yxpv7xR3g
    order-channel: "#mybeautip-plus-dev"
  aws:
    s3:
      domain: 'https://mybeautip-plus-dev.s3.ap-southeast-1.amazonaws.com/'
      bucket: 'mybeautip-plus-dev'
      region: 'ap-southeast-1'
    cf:
      domain: "https://static-dev.mybeautip.me/"

#redis:
#  host: common-elasticache.ntbzpm.clustercfg.apn2.cache.amazonaws.com
#  port: 6379

logging:
  config: classpath:log/log4j2-console.yml


