spring:
  config:
    activate:
      on-profile: production
    import: classpath:application-oauth-prod.yml
  datasource:
    url: jdbc:mysql://172.31.2.106:3306/mybeautip?zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: mybeautip
    password: akdlqbxlq#1@Jocoos
    test-on-borrow: true
    validation-query: SELECT 1
  flyway:
    baselineOnMigrate: false
    locations: classpath:db/mysql

mybeautip:
  security:
    access-token-validity-seconds: 15552000      # 180 days
    refresh-token-validity-seconds: 15552000     # 180 days
  aws:
    sns:
      application:
        gcm-arn: "arn:aws:sns:ap-northeast-2:776875668468:app/GCM/mybeautip"
    s3:
      bucket: 'mybeautip-prod'
      region: 'ap-northeast-2'
  slack:
    key: T03FMJ9ANNR/B03FT8YFXC5/GFY50VQh98iRpEs4XbmxmrYP
    channel: "#mybeautip-prod"
    order-key: T02GN94AU/BKB98G20Z/mula9sD6NE9rpxIhuRWUePwH
    order-channel: "#z-mybeautip-order"
  iamport:
    api: https://api.iamport.kr
    key: 3621612290867148
    secret: Z4CYi1YGDdOfk2ti4mYQtpEJiJPfxzlxEXvWZtCCGqR1skjxHinaI1U1LJgijBPXzlTyOwavW2xpmRW4

cloud:
  aws:
    s3:
      bucket: mybeautip-prod

flipflop:
  app-key: 9z27htVnKe
  video:
    thumbnail-format: https://flipflop-prod.s3.ap-northeast-2.amazonaws.com/${flipflop.app-key}/videos/%s/thumbnail.jpg

redis:
  host: 172.31.2.106
  port: 6379
  password: akdlqbxlq#1@Jocoos

logging:
  config: classpath:log/log4j2-file.yml