spring:
  config:
    activate:
      on-profile: qa
    import: classpath:application-oauth-dev.yml
  datasource:
    master:
      hikari:
        username: mybeautipqasrv
        password: mybeautipqasrvpass77
        jdbc-url: jdbc:mysql://rds-mybeautip-qa.cluster-cznmmhv51m5v.ap-northeast-2.rds.amazonaws.com:13305/mybeautip?allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    slave:
      hikari:
        username: mybeautipqasrv
        password: mybeautipqasrvpass77
        jdbc-url: jdbc:mysql://rds-mybeautip-qa.cluster-cznmmhv51m5v.ap-northeast-2.rds.amazonaws.com:13305/mybeautip?allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF-8&useSSL=false
mybeautip:
  store:
    image-path:
      domain: https://static.mybeautip.com/common/
  security:
    access-token-validity-seconds: 604800     # 7 hours
    refresh-token-validity-seconds: 1814400    # 21 days
  slack:
    key: T03FMJ9ANNR/B03GKUDN78Q/OG75R443el0aPxJ2sQdZl8Xd
    channel: "#mybeautip-dev"
    order-key: T03FMJ9ANNR/B03GKUDN78Q/OG75R443el0aPxJ2sQdZl8Xd
    order-channel: "#mybeautip-dev"



