spring:
  security:
    oauth2:
      client:
        provider:
          kakao:
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            client-id: 24c07e1aa425eee8ff33dc762bb52578
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:3000/oauth
          naver:
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            client-id: u6IHjY5nYFx76BSlFxmC
            client-secret: S0Ss6qUwsP
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:3000/oauth
            state: mybeautip-web-mobile
          facebook:
            token-uri: https://graph.facebook.com/v13.0/oauth/access_token
            token-method: GET
            user-info-uri: https://graph.facebook.com/me
            client-id: 448301395614533
            client-secret: 8da721bd036785894dda7b8f4963d211
            redirect-uri: http://localhost:3000/oauth
            state: mybeautip-web-mobile
            fields: id,email,name,picture