ALTER TABLE `goods` MODIFY COLUMN `like_count` INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `stores` MODIFY COLUMN `goods_count` INT UNSIGNED DEFAULT 0;
ALTER TABLE `stores` MODIFY COLUMN `like_count` INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `posts` MODIFY COLUMN `view_count` INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `posts` MODIFY COLUMN `like_count` INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `posts` MODIFY COLUMN `comment_count` INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `videos` MODIFY COLUMN `watch_count` INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `videos` MODIFY COLUMN `total_watch_count` INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `videos` MODIFY COLUMN `heart_count` INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `videos` MODIFY COLUMN `view_count` INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `videos` MODIFY COLUMN `comment_count` INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `videos` MODIFY COLUMN `like_count` INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `videos` MODIFY COLUMN `order_count` INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `videos` MODIFY COLUMN `related_goods_count` TINYINT UNSIGNED DEFAULT 0;
ALTER TABLE `videos` MODIFY COLUMN `muted` TINYINT(1) DEFAULT 0;
ALTER TABLE `comments` MODIFY COLUMN `like_count` INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `comments` MODIFY COLUMN `comment_count` INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `video_views` MODIFY COLUMN `view_count` INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `view_recodings` MODIFY COLUMN `view_count` INT UNSIGNED DEFAULT 0;
ALTER TABLE `carts` MODIFY COLUMN `quantity` INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `member_points` MODIFY COLUMN `point` INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `tags` MODIFY COLUMN `ref_count` INT UNSIGNED DEFAULT 0;


-- DELETE FROM flyway_schema_history WHERE version='0112';
