ALTER TABLE `notifications` MODIFY COLUMN `image_url` VARCHAR(500) DEFAULT NULL;

ALTER TABLE `goods_categories` MODIFY COLUMN `thumbnail_url` VARCHAR(500) DEFAULT NULL;

ALTER TABLE `videos` MODIFY COLUMN `related_goods_thumbnail_url` VARCHAR(500) DEFAULT NULL;

ALTER TABLE `stores` MODIFY COLUMN `image_url` VARCHAR(500) DEFAULT NULL;

ALTER TABLE `stores` MODIFY COLUMN `thumbnail_url` VARCHAR(500) DEFAULT NULL;

ALTER TABLE `stores` MODIFY COLUMN `refund_url` VARCHAR(500) DEFAULT NULL;

ALTER TABLE `stores` MODIFY COLUMN `as_url` VARCHAR(500) DEFAULT NULL;

ALTER TABLE `schedules` MODIFY COLUMN `thumbnail_url` VARCHAR(500) DEFAULT NULL;

-- DELETE FROM flyway_schema_history WHERE version='0128';
-- ALTER TABLE `notifications` MODIFY COLUMN `image_url` VARCHAR(255) DEFAULT NULL;

-- ALTER TABLE `goods_categories` MODIFY COLUMN `thumbnail_url` VARCHAR(255) DEFAULT NULL;

-- ALTER TABLE `videos` MODIFY COLUMN `related_goods_thumbnail_url` VARCHAR(255) DEFAULT NULL;

-- ALTER TABLE `stores` MODIFY COLUMN `image_url` VARCHAR(255) DEFAULT NULL;
-- ALTER TABLE `stores` MODIFY COLUMN `thumbnail_url` VARCHAR(255) DEFAULT NULL;
-- ALTER TABLE `stores` MODIFY COLUMN `refund_url` VARCHAR(255) DEFAULT NULL;
-- ALTER TABLE `stores` MODIFY COLUMN `as_url` VARCHAR(255) DEFAULT NULL;

-- ALTER TABLE `schedules` MODIFY COLUMN `thumbnail_url` VARCHAR(200) DEFAULT NULL;
