version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo start gradle build
      - ./gradlew build -Dprofile=dev
      - echo end of gradle build
      - ls -al build/libs/
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 904235351504.dkr.ecr.ap-southeast-1.amazonaws.com
      - REPOSITORY_URI=904235351504.dkr.ecr.ap-southeast-1.amazonaws.com/mybeautip-api
      - IMAGE_TAG=dev
  build:
    commands:
      - echo start docker build
      - docker build -f plus/Dockerfile -t $REPOSITORY_URI:$IMAGE_TAG .
      - echo end of docker build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"mybeautip-api","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
      
artifacts:
  files:
    - imagedefinitions.json

cache:
  paths:
    - '/root/.gradle/caches/**/*'
